name: "Build predtimechart dashboard (new)"
on:
  workflow_dispatch:
  repository_dispatch:
    types: ["registration"]

jobs:
  repos:
    name: "Get list of dashboard repositories"
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/get-installations.yaml@main
    with:
      newbies: '${{ github.event.client_payload.newbies }}'
    secrets:
      id: ${{ vars.APP_ID }}
      key: ${{ secrets.PRIVATE_KEY }}
  echo:
    name: "echo me"
    needs: [repos]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.repos.outputs.repos }}
