name: "Build predtimechart dashboard (new)"
on:
  workflow_dispatch:
  repository_dispatch:
    types: ["registration"]

jobs:
  repos:
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/get-installations.yaml@main
    with:
      newbies: '${{ toJSON(github.event.client_payload.newbies) }}'
    secrets:
      id: ${{ vars.APP_ID }}
      key: ${{ secrets.PRIVATE_KEY }}
  echo:
    name: "echo me"
    needs: [repos]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.repos.outputs.repos }}
  site:
    needs: [repos]
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/build-site.yaml@main
    with:
      repos: '${{ needs.repos.outputs.repos }}'
      slug: '${{ needs.repos.outputs.slug }}'
      email: '${{ needs.repos.outputs.email }}'
