name: "Build predtimechart dashboard"
on:
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish Site (uncheck for a dry run)"
        type: boolean
        required: false
        default: true

  repository_dispatch:
    types:
      - "registration"
      - "all"
  schedule:
    - cron: "17 19 * * *"

jobs:
  repos:
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/get-installations.yaml@main
    with:
      newbies: ${{ toJSON(github.event.client_payload.newbies) }}
    secrets:
      id: ${{ vars.APP_ID }}
      key: ${{ secrets.PRIVATE_KEY }}
  site:
    needs: [repos]
    strategy:
      matrix:
        site: ${{ fromJSON(needs.repos.outputs.repos) }}
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/generate-site.yaml@main
    with:
      owner: '${{ matrix.site.owner }}'
      name: '${{ matrix.site.name }}'
      slug: '${{ needs.repos.outputs.slug }}'
      email: '${{ needs.repos.outputs.email }}'
      publish: ${{ inputs.publish }}
    secrets:
      id: ${{ vars.APP_ID }}
      key: ${{ secrets.PRIVATE_KEY }}
  data:
    needs: [repos]
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/generate-data.yaml@main
    with:
      repos: '${{ needs.repos.outputs.repos }}'
      slug: '${{ needs.repos.outputs.slug }}'
      email: '${{ needs.repos.outputs.email }}'
    secrets:
      id: ${{ vars.APP_ID }}
      key: ${{ secrets.PRIVATE_KEY }}
