name: "Filter Matrix Jobs"
defaults:
  run:
    shell: bash
on:
  workflow_call:
    inputs:
      artifact:
        required: true
        type: string
    outputs:
      matrix:
        description: "A JSON list containing the filtered jobs that can be run further"
        value: ${{ jobs.check.outputs.mat }}
      process:
        description: "A boolean value indicating that the result should be processed"
        value: ${{ jobs.check.outputs.process }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      mat: ${{ steps.list.outputs.ok }}
      process: ${{ steps.list.outputs.process }}
    steps:
      - id: fetch-artifacts
        uses: actions/download-artifact@v4
        with:
          path: results
          pattern: ${{ inputs.artifact }}
          merge-multiple: true
      - id: list
        run: |
          if [[ ! -d results ]]; then
            echo "process=false" >> "$GITHUB_OUTPUT"
            echo "ok=[]" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "process=true" >> "$GITHUB_OUTPUT"
          res=(results/*)
          cat ${res[0]}
          {
            echo "ok<<EOF"
            # combine the files in results into one array
            jq '.' results/* | jq -s .
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
