name: "Generate Target and Forecast Data"
defaults:
  run:
    shell: bash
on:
  workflow_call:
    inputs:
      repos:
        required: true
        type: string
      slug:
        required: true
        type: string
      email:
        required: true
        type: string
      regenerate:
        default: false
        required: false
        type: boolean
    secrets:
      id:
        required: true
      key:
        required: true

jobs:
  check:
    name: "Check Bot Status"
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.bot.outputs.bot }}
    steps:
      - id: bot
        name: "Check if we are running a bot"
        run: |
          if [[ "${{ secrets.id }}" = "none" ]]; then
            bot=false
          else
            bot=true
          fi
          echo "bot=$bot" >> "$GITHUB_OUTPUT"
  build-evals:
    needs: [check]
    name: "Generate Eval Page Data"
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      ok: ${{ fromJSON(steps.status-check.outputs.ok) }}
    env:
      KEY: ${{ matrix.site.owner }}-${{ matrix.site.name }}
    strategy:
      matrix:
        site: ${{ fromJSON(inputs.repos) }}
    container:
      image: ghcr.io/hubverse-org/hubpredevalsdata-docker:main
      ports:
        - 80
      volumes:
        - ${{ github.workspace }}:/project
    steps:
      - id: id
        name: "setup run variables"
        run: |
          if [[ -n "${{ matrix.site.build }}" ]]; then
            echo "build=${{ matrix.site.build }}" >> $GITHUB_OUTPUT
          else
            echo "build=both" >> $GITHUB_OUTPUT
          fi
          owner="${{ matrix.site.owner }}"
          name="${{ matrix.site.name }}"
          echo "repo=$owner/$name" >> $GITHUB_OUTPUT
          echo "file=$owner-$name-predeval" >> $GITHUB_OUTPUT
      - uses: actions/create-github-app-token@v1
        if: ${{ fromJSON(needs.check.outputs.exists) }}
        id: token
        with:
          app-id: ${{ secrets.id }}
          private-key: ${{ secrets.key }}
          owner: ${{ matrix.site.owner }}
          repositories: ${{ matrix.site.name }}
      - id: checkout-config
        name: "Fetch config files"
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ steps.token.outputs.token || secrets.key }}
          repository: ${{ steps.id.outputs.repo }}
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            predeval-config.yml
            site-config.yml
      - id: status-check
        name: "Check if we need to build data"
        run: |
          if [[ ! -f predeval-config.yml ]]; then
            echo "ok=false" >> "$GITHUB_OUTPUT"
            repo=${{ steps.id.outputs.repo }}
            echo "::notice title=Missing config ($repo)::No predeval-config.yml file found. Exiting."
            exit 0
          fi
          file=evals-${{ env.KEY }}
          touch "$file"
          {
            echo '${{ toJSON(matrix.site) }}'
          } > "$file"
          echo "ok=true" >> $GITHUB_OUTPUT
      - id: upload-status
        if: ${{ fromJSON(steps.status-check.outputs.ok) }}
        uses: actions/upload-artifact@v4
        with:
          name: evals-${{ env.KEY }}
          path: evals-${{ env.KEY }}
      - id: check-branch
        if: ${{ fromJSON(steps.status-check.outputs.ok) }}
        name: "check for predeval/data branch"
        env:
          GH_TOKEN: ${{ steps.token.outputs.token || secrets.key }}
        run: | 
          exists=$(curl -sSL "https://api.github.com/repos/${{ steps.id.outputs.repo }}/branches" | jq '.[].name | select(. == "predeval/data")')
          if [[ "$exists" = "predeval/data" ]]; then
            fetch=true
          else
            fetch=false
          fi
          echo "fetch=$fetch" >> "$GITHUB_OUTPUT"
      - id: checkout-data
        if: ${{ fromJSON(steps.status-check.outputs.ok) && fromJSON(steps.check-branch.outputs.fetch) }}
        name: "Checkout predeval/data branch"
        uses: actions/checkout@v4
        with:
          token: ${{ steps.token.outputs.token || secrets.key }}
          persist-credentials: false
          repository: ${{ steps.id.outputs.repo }}
          ref: 'predeval/data'
          path: 'out'
      - id: get-repo-name
        if: ${{ fromJSON(steps.status-check.outputs.ok) }}
        name: "Get information about hub"
        run: |
          mkdir -p out/
          yq eval '.hub' site-config.yml \
          | sed -E -e 's+(https://github.com/|^)+repo=+' \
          | sed -E -e 's+[/]$++' >> $GITHUB_OUTPUT
      - id: clone-repo
        if: ${{ fromJSON(steps.status-check.outputs.ok) }}
        name: "Fetch ${{ steps.get-repo-name.outputs.repo }}"
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          repository: ${{ steps.get-repo-name.outputs.repo }}
          path: 'repo'
      - id: build-targets
        if: ${{ fromJSON(steps.status-check.outputs.ok) }}
        name: "Generate scores data"
        run: |
          prefix="https://raw.githubusercontent.com/${{ steps.id.outputs.repo }}/refs/heads"
          oracle="${prefix}/oracle-data/oracle-output.csv"
          create-predeval-data.R \
          -h repo \
          -c predeval-config.yml \
          -d $oracle \
          -o out
      - name: Upload artifact
        if: ${{ fromJSON(steps.status-check.outputs.ok) }}
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.id.outputs.file }}
          path: 'out/'
  build-forecasts:
    needs: [check]
    name: "Generate Forecast Page Data"
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      ok: ${{ fromJSON(steps.status-check.outputs.ok) }}
    env:
      KEY: ${{ matrix.site.owner }}-${{ matrix.site.name }}
    strategy:
      matrix:
        site: ${{ fromJSON(inputs.repos) }}
    steps:
      - id: id
        name: "setup run variables"
        run: |
          if [[ -n "${{ matrix.site.build }}" ]]; then
            echo "build=${{ matrix.site.build }}" >> $GITHUB_OUTPUT
          else
            echo "build=both" >> $GITHUB_OUTPUT
          fi
          owner="${{ matrix.site.owner }}"
          name="${{ matrix.site.name }}"
          echo "repo=$owner/$name" >> $GITHUB_OUTPUT
          echo "file=$owner-$name-ptc" >> $GITHUB_OUTPUT
      - uses: actions/create-github-app-token@v1
        if: ${{ fromJSON(needs.check.outputs.exists) }}
        id: token
        with:
          app-id: ${{ secrets.id }}
          private-key: ${{ secrets.key }}
          owner: ${{ matrix.site.owner }}
          repositories: ${{ matrix.site.name }}
      - id: checkout-config
        name: "Fetch config files"
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ steps.token.outputs.token || secrets.key }}
          repository: ${{ steps.id.outputs.repo }}
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            predtimechart-config.yml
            site-config.yml
      - id: status-check
        name: "Check if we need to build data"
        run: |
          if [[ ! -f predtimechart-config.yml ]]; then
            echo "ok=false" >> "$GITHUB_OUTPUT"
            repo=${{ steps.id.outputs.repo }}
            echo "::notice title=Missing config ($repo)::No predtimechart-config.yml file found. Exiting."
            exit 0
          fi
          file=ptc-${{ env.KEY }}
          touch "$file"
          {
            echo '${{ toJSON(matrix.site) }}'
          } > "$file"
          echo "ok=true" >> $GITHUB_OUTPUT
      - id: setup-snake
        if: ${{ fromJSON(steps.status-check.outputs.ok) }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - id: install-predtimechart-tool
        name: "Install predtimechart conversion tool"
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/hubverse-org/hub-dashboard-predtimechart
      - id: upload-status
        if: ${{ fromJSON(steps.status-check.outputs.ok) }}
        uses: actions/upload-artifact@v4
        with:
          name: ptc-${{ env.KEY }}
          path: ptc-${{ env.KEY }}
      - id: check-branch
        if: ${{ fromJSON(steps.status-check.outputs.ok) }}
        name: "check for ptc/data branch"
        env:
          GH_TOKEN: ${{ steps.token.outputs.token || secrets.key }}
        run: | 
          exists=$(gh api -X GET "repos/${{ steps.id.outputs.repo }}/branches" --jq '.[].name | select(. == "ptc/data")')
          if [[ "$exists" = "ptc/data" ]]; then
            fetch=true
          else
            fetch=false
          fi
          echo "fetch=$fetch" >> "$GITHUB_OUTPUT"
      - id: checkout-data
        if: ${{ fromJSON(steps.status-check.outputs.ok) && fromJSON(steps.check-branch.outputs.fetch) }}
        name: "Checkout ptc/data branch"
        uses: actions/checkout@v4
        with:
          token: ${{ steps.token.outputs.token || secrets.key }}
          persist-credentials: false
          repository: ${{ steps.id.outputs.repo }}
          ref: 'ptc/data'
          path: 'out'
      - id: get-repo-name
        if: ${{ fromJSON(steps.status-check.outputs.ok) }}
        name: "Get information about hub"
        run: |
          mkdir -p out/targets/
          mkdir -p out/forecasts/
          yq eval '.hub' site-config.yml \
          | sed -E -e 's+(https://github.com/|^)+repo=+' \
          | sed -E -e 's+[/]$++' >> $GITHUB_OUTPUT
      - id: clone-repo
        if: ${{ fromJSON(steps.status-check.outputs.ok) }}
        name: "Fetch ${{ steps.get-repo-name.outputs.repo }}"
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          repository: ${{ steps.get-repo-name.outputs.repo }}
          path: 'repo'
      - id: build-targets
        name: "Generate target data"
        if: ${{ fromJSON(steps.status-check.outputs.ok) && steps.id.outputs.build == 'both' || steps.id.outputs.build == 'target' }}
        run: |
          ptc_generate_target_json_files \
            repo \
            predtimechart-config.yml \
            out/targets
      - id: json-lives
        if: ${{ fromJSON(steps.status-check.outputs.ok) && steps.id.outputs.build == 'both' || steps.id.outputs.build == 'forecast' }}
        name: "Generate forecast data"
        run: |
          if [[ ${{ inputs.regenerate }} == 'true' ]]; then
            ptc_generate_json_files \
              repo \
              predtimechart-config.yml \
              out/predtimechart-options.json \
              out/forecasts \
              --regenerate
          else
            ptc_generate_json_files \
              repo \
              predtimechart-config.yml \
              out/predtimechart-options.json \
              out/forecasts
          fi
      - name: Upload artifact
        if: ${{ fromJSON(steps.status-check.outputs.ok) }}
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.id.outputs.file }}
          path: 'out/'
  check-forecasts:
    runs-on: ubuntu-latest
    needs: [build-forecasts]
    outputs:
      mat: ${{ steps.list.outputs.ok }}
      process: ${{ steps.list.outputs.process }}
    steps:
      - id: fetch-artifacts
        uses: actions/download-artifact@v4
        with:
          path: results
          pattern: ptc-*
          merge-multiple: true
      - id: list
        run: |
          if [[ ! -d results ]]; then
            echo "process=false" >> "$GITHUB_OUTPUT"
            echo "ok=[]" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "process=true" >> "$GITHUB_OUTPUT"
          res=(results/*)
          cat ${res[0]}
          {
            echo "ok<<EOF"
            # combine the files in results into one array
            jq '.' results/* | jq -s .
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
  push-ptc-data:
    needs: [check, check-forecasts]
    if: ${{ needs.check-forecasts.outputs.process }}
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/push-things.yaml@znk/hub-evals
    strategy: 
      matrix: 
        site: ${{ fromJSON(needs.check-forecasts.outputs.mat) }}
    with:
      is_bot: ${{ fromJSON(needs.check.outputs.exists) }}
      branch: "ptc/data"
      artifact: ${{ matrix.site.owner }}-${{ matrix.site.name }}-ptc
      owner: ${{ matrix.site.owner }}
      name: ${{ matrix.site.name }}
      slug: ${{ inputs.slug }}
      email: ${{ inputs.email }}
    secrets: inherit
  check-predeval:
    runs-on: ubuntu-latest
    needs: [build-evals]
    outputs:
      mat: ${{ steps.list.outputs.ok }}
      process: ${{ steps.list.outputs.process }}
    steps:
      - id: fetch-artifacts
        uses: actions/download-artifact@v4
        with:
          path: results
          pattern: evals-*
          merge-multiple: true
      - id: list
        run: |
          if [[ ! -d results ]]; then
            echo "process=false" >> "$GITHUB_OUTPUT"
            echo "ok=[]" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "process=true" >> "$GITHUB_OUTPUT"
          res=(results/*)
          cat ${res[0]}
          {
            echo "ok<<EOF"
            # combine the files in results into one array
            jq '.' results/* | jq -s .
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
  push-predeval-data:
    needs: [check, check-predeval]
    if: ${{ needs.check-predeval.outputs.process }}
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/push-things.yaml@znk/hub-evals
    strategy:
      matrix:
        site: ${{ fromJSON(needs.check-predeval.outputs.mat) }}
    with:
      is_bot: ${{ fromJSON(needs.check.outputs.exists) }}
      branch: "predeval/data"
      artifact: ${{ matrix.site.owner }}-${{ matrix.site.name }}-predeval
      owner: ${{ matrix.site.owner }}
      name: ${{ matrix.site.name }}
      slug: ${{ inputs.slug }}
      email: ${{ inputs.email }}
    secrets: inherit
