name: "Generate Static Site"
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      repos:
        required: true
        type: string
      slug:
        required: true
        type: string
      email:
        required: true
        type: string
    secrets:
      id:
        required: true
      key:
        required: true

jobs:
  build-site:
    name: "Build Site"
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      success: ${{ steps.result.outputs.success }}
    strategy: 
      matrix: 
        site: ${{ fromJSON(inputs.repos) }}
    container:
      image: ghcr.io/hubverse-org/hub-dash-site-builder:main
      ports:
        - 80
      volumes:
        - ${{ github.workspace }}:/site
    steps:
      - uses: actions/create-github-app-token@v1
        name: "Generate App Token (if no token present)"
        id: token
        with:
          app-id: ${{ secrets.id }}
          private-key: ${{ secrets.key }}
          owner: ${{ matrix.site.owner }}
          repositories: ${{ matrix.site.name }}
      - id: id
        run: |
          owner="${{ matrix.site.owner }}"
          name="${{ matrix.site.name }}"
          echo "repo=$owner/$name" >> $GITHUB_OUTPUT
          echo "file=$owner-$name-site" >> $GITHUB_OUTPUT
      - id: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.token.outputs.token }}
          persist-credentials: false
          repository: ${{ steps.id.outputs.repo }}
      - id: check-configs
        name: "Check if we need to build site"
        run: |
          if [[ ! -f site-config.yml ]]; then
            echo "::error title=Missing config::No `site-config.yml` file found. Exiting."
            exit 1
          fi
          if [[ -f predtimechart-config.yml ]]; then
            echo "forecasts=true" >> $GITHUB_OUTPUT
          else
            echo "forecasts=false" >> $GITHUB_OUTPUT
          fi
      - id: build-site
        name: "Render Website"
        run: |
          bash /render.sh \
            "${{ matrix.site.owner }}" \
            "${{ matrix.site.name }}" \
            "ptc/data" \
            "" \
            "${{ steps.check-configs.outputs.forecasts }}" \
          && echo "success=true" >> $GITHUB_OUTPUT \
          || echo "success=false" >> $GITHUB_OUTPUT
      - name: Upload artifact
        # if: ${{ steps.build-site.outputs.success == true }}
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.id.outputs.file }}
          path: '/site/pages/'
          retention-days: 1
      # - name: signal success
      #   # if: ${{ steps.build-site.outputs.success == true }}
      #   run: |
      #     touch "${{runner.temp}}/${{steps.id.outputs.file}}.success" 
  push-site:
    name: "Push Site"
    runs-on: ubuntu-latest
    needs: [build-site]
    continue-on-error: true
    strategy:
      matrix:
        site: ${{ fromJSON(inputs.repos) }}
    steps:
      - id: id
        run: |
          owner="${{ matrix.site.owner }}"
          name="${{ matrix.site.name }}"
          echo "repo=$owner/$name" >> $GITHUB_OUTPUT
          echo "file=$owner-$name-site" >> $GITHUB_OUTPUT
          if [[ -f "${{runner.temp}}/$owner-$name-site.success" ]];
          then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi
      - id: checkout-this-here-repo-scripts
        uses: actions/checkout@v4
        with:
          repository: hubverse-org/hub-dashboard-control-room
          persist-credentials: false
          sparse-checkout: |
            scripts
      - uses: actions/create-github-app-token@v1
        id: token
        with:
          app-id: ${{ secrets.id }}
          private-key: ${{ secrets.key }}
          owner: ${{ matrix.site.owner }}
          repositories: ${{ matrix.site.name }}
      - id: check-branch
        env:
          GH_TOKEN: ${{ github.token }}
        name: "check for gh-pages branch and create if needed"
        run: | 
          bash -x "${{ github.workspace }}/scripts/check-branch.sh" \
            "gh-pages" \
            "${{ steps.id.outputs.repo }}" \
            "${{ inputs.slug }}" \
            "${{ inputs.email }}" \
            "${{ steps.token.outputs.token }}"
      - id: checkout-pages
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          repository: ${{ steps.id.outputs.repo }}
          ref: gh-pages
          path: 'pages'
          token: ${{ steps.token.outputs.token }}
      - id: fetch-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.id.outputs.file }}
      - id: publish
        run: |
          bash -x "${{ github.workspace }}/scripts/pushit.sh" \
            "gh-pages" \
            "${{ steps.id.outputs.repo }}" \
            "${{ inputs.slug }}" \
            "${{ inputs.email }}" \
            "${{ steps.token.outputs.token }}"
