name: "Generate Static Site"
defaults:
  run:
    shell: bash
on:
  workflow_call:
    inputs:
      repos:
        required: false
        type: string
      owner:
        required: false
        type: string
      name:
        required: false
        type: string
      slug:
        required: true
        type: string
      email:
        required: true
        type: string
      publish:
        required: false
        type: boolean
        default: true
    secrets:
      id:
        required: true
      key:
        required: true

env:
  OWNER: ${{ inputs.owner || fromJSON(inputs.repos)[0].owner }}
  REPO: ${{ inputs.name || fromJSON(inputs.repos)[0].name }}

jobs:
  build-site:
    name: "Build Site"
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      owner: ${{ steps.id.outputs.owner }}
      name: ${{ steps.id.outputs.name }}
      success: ${{ steps.build-site.outputs.success }}
      is-bot: ${{ steps.is-bot.outputs.bot }}
    container:
      image: ghcr.io/hubverse-org/hub-dash-site-builder:znk-dispatch-fix-34
      ports:
        - 80
      volumes:
        - ${{ github.workspace }}:/site
    steps:
      - id: is-bot
        env:
          BOT_ID: ${{ secrets.id }}
        name: "Check if we are running a bot"
        run: |
          if [[ "$BOT_ID" = "none" ]]; then
            bot=false
          else
            bot=true
          fi
          echo "bot is $bot"
          echo "bot=$bot" >> "$GITHUB_OUTPUT"
        shell: bash
      - uses: actions/create-github-app-token@v1
        if: ${{ fromJSON(steps.is-bot.outputs.bot) }}
        name: "Generate App Token (if no token present)"
        id: token
        with:
          app-id: ${{ secrets.id }}
          private-key: ${{ secrets.key }}
          owner: ${{ env.OWNER }}
          repositories: ${{ env.REPO }}
      - id: id
        name: "setup run variables"
        run: |
          owner="$OWNER"
          name="$REPO"
          echo "owner=$owner" >> $GITHUB_OUTPUT
          echo "name=$name" >> $GITHUB_OUTPUT
          echo "repo=$owner/$name" >> $GITHUB_OUTPUT
          echo "file=$owner-$name-site" >> $GITHUB_OUTPUT
      - id: checkout
        name: "Fetch ${{ steps.id.outputs.repo }}"
        uses: actions/checkout@v4
        with:
          token: ${{ steps.token.outputs.token || secrets.key }}
          persist-credentials: false
          repository: ${{ steps.id.outputs.repo }}
      - id: check-configs
        name: "Check if we need to build site"
        shell: "bash"
        env:
          REPO: ${{ steps.id.outputs.repo }}
        run: |
          if [[ ! -f site-config.yml ]]; then
            echo "::error title=Missing config ($REPO)::No site-config.yml file found. Exiting."
            exit 1
          fi
      - id: build-site
        name: "Render Website"
        run: render.sh -u "$OWNER" -r "$REPO"
      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.id.outputs.file }}
          path: '/site/pages/'
          retention-days: 1
  push-site:
    name: "Push Site"
    permissions:
      contents: write
    needs: [build-site]
    if: ${{ inputs.publish }}
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/push-things.yaml@main
    with:
      is_bot: ${{ fromJSON(needs.build-site.outputs.is-bot) }}
      branch: "gh-pages"
      artifact: ${{ needs.build-site.outputs.owner }}-${{ needs.build-site.outputs.name }}-site
      owner: ${{ needs.build-site.outputs.owner}}
      name: ${{ needs.build-site.outputs.name }}
      slug: ${{ inputs.slug }}
      email: ${{ inputs.email }}
    secrets: inherit
