name: "Push To Branch"
defaults:
  run:
    shell: bash
on:
  workflow_call:
    inputs:
      is_bot:
        required: true
        type: boolean
      branch:
        required: true
        type: string
      artifact:
        required: true
        type: string
      owner:
        required: true
        type: string
      name:
        required: true
        type: string
      slug:
        required: true
        type: string
      email:
        required: true
        type: string
    secrets:
      id:
        required: true
      key:
        required: true

jobs:
  push-data:
    name: "Push Data"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - id: checkout-this-here-repo-scripts
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: hubverse-org/hub-dashboard-control-room
          ref: main
          persist-credentials: false
          sparse-checkout: |
            scripts
      - id: id
        name: "setup run variables"
        run: |
          owner="${{ inputs.owner }}"
          name="${{ inputs.name }}"
          echo "repo=$owner/$name" >> $GITHUB_OUTPUT
      - uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09
        if: ${{ fromJSON(inputs.is_bot) }}
        id: token
        with:
          app-id: ${{ secrets.id }}
          private-key: ${{ secrets.key }}
          owner: ${{ inputs.owner }}
          repositories: ${{ inputs.name }}
      - id: check-branch
        env:
          GH_TOKEN: ${{ github.token }}
        name: "check for ${{ inputs.branch }}branch and create if needed"
        run: |
          bash -x "${{ github.workspace }}/scripts/check-branch.sh" \
            "${{ inputs.branch }}" \
            "${{ steps.id.outputs.repo }}" \
            "${{ inputs.slug }}" \
            "${{ inputs.email }}" \
            "${{ steps.token.outputs.token || secrets.key }}"
      - id: checkout-data
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
          repository: ${{ steps.id.outputs.repo }}
          ref: ${{ inputs.branch }}
          path: 'data'
          token: ${{ steps.token.outputs.token || secrets.key }}
      - id: fetch-artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e
        with:
          name: ${{ inputs.artifact }}
      - id: publish
        name: "Publish to ${{ inputs.branch }} branch"
        run: | 
          ls -larth
          bash -x "${{ github.workspace }}/scripts/pushit.sh" \
            "${{ inputs.branch }}" \
            "${{ steps.id.outputs.repo }}" \
            "${{ inputs.slug }}" \
            "${{ inputs.email }}" \
            "${{ steps.token.outputs.token || secrets.key }}"
