name: "Rebuild Site"
on:
  workflow_dispatch:
  repository_dispatch:
    types: ["site"]

jobs:
  repos:
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/get-installations.yaml@main
    with:
      newbies: '${{ toJSON(github.event.client_payload.newbies) }}'
    secrets:
      id: ${{ vars.APP_ID }}
      key: ${{ secrets.PRIVATE_KEY }}
  site:
    needs: [repos]
    matrix:
      site: ${{ fromJSON(needs.repos.outputs.repos) }}
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/generate-site.yaml@znk/move-matrix/14
    with:
      owner: '${{ matrix.site.owner }}'
      name: '${{ matrix.site.name }}'
      slug: '${{ needs.repos.outputs.slug }}'
      email: '${{ needs.repos.outputs.email }}'
      publish: false
    secrets:
      id: ${{ vars.APP_ID }}
      key: ${{ secrets.PRIVATE_KEY }}
