name: "Rebuild Site"
on:
  workflow_dispatch:
  repository_dispatch:
    types: ["site"]

jobs:
  repos:
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/get-installations.yaml@znk/no-token
    with:
      newbies: '${{ toJSON(github.event.client_payload.newbies) }}'
    secrets:
      id: ${{ vars.APP_ID }}
      key: ${{ secrets.PRIVATE_KEY }}
  site:
    needs: [repos]
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/generate-site.yaml@znk/no-token
    with:
      repos: '${{ needs.repos.outputs.repos }}'
      slug: '${{ needs.repos.outputs.slug }}'
      email: '${{ needs.repos.outputs.email }}'
    secrets:
      id: ${{ vars.APP_ID }}
      key: ${{ secrets.PRIVATE_KEY }}
